# This is a basic workflow to help you get started with Actions

name: deploy-dreamweb

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: releases/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # - name: deploy via ssh
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.PASSWORD }}
      #     port: ${{ secrets.PORT }}
      #     script: /home/admin/deploy_dreamweb.sh
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: notify to dingding
        run: |
          curl --location --request POST 'https://oapi.dingtalk.com/robot/send?access_token=${{ secrets.dingding_access_token }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "msgtype": "markdown",
              "markdown": {
                  "title": "Dreamweb Deploy",
                  "text": "### Dreamweb Deploy \n\n-----------------  \n\n [version] \n\n  ${{ steps.vars.outputs.tag }}  \n\n [message] \n\n  ${{ github.event.head_commit.message }}  \n\n [author] \n\n  ${{ github.actor }}"
              }
          }'
